### ISSUE TITLE
error: use of undeclared identifier 'eglGetProcAddress'

### ISSUE THREAD

**Issue by yonas** [bvisness/SQLJam#1]
I'm getting the following compiling error:

```
$ go run main.go
# github.com/gen2brain/raylib-go/raylib
core.c:962:1: warning: non-void function does not return a value [-Wreturn-type]
core.c:2540:1: warning: non-void function does not return a value [-Wreturn-type]
core.c:4361:22: error: use of undeclared identifier 'eglGetProcAddress'

```

FreeBSD 13.1
Go 1.18.4

**Comment by bvisness** [comment]
That's an issue with the Raylib bindings, which are a third-party library. It's not something I have control over. I would recommend creating an issue on https://github.com/gen2brain/raylib-go instead.
