### ISSUE TITLE
Please add LICENSE for this repository

### ISSUE THREAD

**Issue by penyuan** [bvisness/SQLJam#2]
Thank you @bvisness for creating such a great visual tool! 🎆 👍🏼  I think it's the perfect solution for exploring and querying certain databases.

Can you please add a `LICENSE` to this repository such as the GNU GPLv3 or similar? This is super easy, just follow the GitHub instructions [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

**Comment by bvisness** [comment]
It's deliberately proprietary. I'm not done with this project and wish to retain all rights. 

If there is some aspect of it you would like to use, then contact me and we can discuss it.

**Comment by penyuan** [comment]
Thank you for the quick response! As a general principle I minimize the amount of proprietary software that I use, so I will not be able to make use of this one. For what it's worth, I will happily pay for this tool if it is fully open source.

Best wishes for your future endeavors!
