### ISSUE TITLE
almost empty screen

### ISSUE THREAD

**Issue by tedstriker** [bvisness/SQLJam#3]
I started the application using go `run main.go` after cloning the repo, but there's only an almost empty screen.
What am I missing?
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/795203/184606856-2e0ba1a6-f731-4908-a93c-388728fd3cbb.png">

**Comment by bvisness** [comment]
No idea. Perhaps a DPI issue, although I thought we fixed the DPI issues? Or maybe something else is going wrong and you should look in the terminal.

Unfortunately I'm not going to offer support for a prototype we made for a jam - I'm sorry if it doesn't work, but if stuff is broken, I'm not going to bother fixing it.
