### ISSUE TITLE
building using docker

### ISSUE THREAD

**Issue by rsubr** [bvisness/SQLJam#4]
Thanks for this great application!

It would be great to teach students in a classroom if this was a web application rather than a native X11 application.

I had some trouble building this, and got the build working in docker with some effort.

Here are my steps to build this in Ubuntu 22.04:

```bash
git clone https://github.com/bvisness/SQLJam.git

docker run -ti --rm -v ${PWD}/SQLJam:/build ubuntu:jammy bash

# You are now inside the docker image
apt update
apt install git golang

apt install libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev \
            libxi-dev libgl1-mesa-dev

cd /build
go build -buildvcs=false

strip SQLJam
```

**Comment by bvisness** [comment]
Cool. This was a jam prototype and not intended for anyone's production use, so "works on my machine" was plenty.
